version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:036861712632:task-definition/tutorial-task-def:3"
        LoadBalancerInfo:
          ContainerName: "sample-app"
          ContainerPort: 80
Hooks:
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:036861712632:function:AfterAllowTestTraffic"